language: node_js
node_js:
  - node
jobs:
  include:
    - stage: test
      name: Util testing
      script: npm test
    - stage: deploy
      name: Deploy to Netlify
      script: curl -X POST -d {} https://api.netlify.com/build_hooks/5dd4106e424e9a1b03cf84af
